"""Real Chromium UI checks. Inline mode works without HTTP navigation; it does not qualify IndexedDB or GPU drivers.
Install test-only dependencies: pip install playwright; playwright install chromium
Run: STRATUM_INLINE_TEST=1 python tests/browser-smoke.py
"""
import asyncio, json, os, pathlib
from playwright.async_api import async_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]
async def main():
 results=[];errors=[]
 async with async_playwright() as playwright:
  executable=os.environ.get('CHROMIUM_PATH')
  if not executable and pathlib.Path('/usr/bin/chromium').exists(): executable='/usr/bin/chromium'
  args=['--no-sandbox']
  if os.environ.get('STRATUM_TEST_SOFTWARE')=='1': args+=['--disable-webgl','--disable-gpu']
  else: args+=['--enable-unsafe-swiftshader']
  browser=await playwright.chromium.launch(executable_path=executable,headless=True,args=args)
  page=await browser.new_page(viewport={'width':1600,'height':1000},device_scale_factor=1)
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('dialog',lambda d:asyncio.create_task(d.accept()))
  if os.environ.get('STRATUM_INLINE_TEST')=='1': await page.set_content((ROOT/'dist/StratumFX.html').read_text(),wait_until='load')
  else: await page.goto(os.environ.get('STRATUM_TEST_URL','http://127.0.0.1:4173/app/?fresh=1'),wait_until='networkidle')
  async def settled():
   await page.wait_for_function('window.stratum && !stratum.cooking && stratum.stats && stratum.viewport?.renderer?.mesh',timeout=30000)
   await page.wait_for_timeout(100)
  async def check(name,expression):
   value=await page.evaluate(expression)
   assert value, f'{name}: {value}'
   results.append({'test':name,'pass':True})
  await settled()
  await check('Initial procedural scene cooks through the worker','stratum.mesh.instanceCount === 1000 && stratum.store.document.nodes.length === 6')
  await check('Renderer canvas contains actual nonuniform pixels', '''async()=>{const b=await stratum.viewport.snapshot();const bitmap=await createImageBitmap(b);const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;const g=c.getContext('2d');g.drawImage(bitmap,0,0);const data=g.getImageData(0,0,c.width,c.height).data;let bright=0;for(let i=0;i<data.length;i+=4)if(data[i]>110&&data[i+1]>95)bright++;return bright>1500;}''')
  await page.locator('#scene-tree [data-node="copy"]').click()
  await check('Scene graph selection populates the parameter editor','document.getElementById("parameters").shadowRoot.textContent.includes("Copy to points")')
  field=page.locator('stratum-parameter-editor input[data-param="scale"][type="text"]')
  if await field.count()==0: field=page.locator('stratum-parameter-editor input[data-param="scale"]').last
  await field.fill('1.2');await field.press('Tab');await settled()
  await check('Parameter edit updates the procedural document','stratum.store.document.nodes.find(n=>n.id==="copy").params.scale===1.2')
  await page.locator('#canvas').focus();await page.keyboard.press('Control+z');await settled()
  await check('Keyboard undo reverses parameter edit','stratum.store.document.nodes.find(n=>n.id==="copy").params.scale===1')
  await page.keyboard.press('Control+Shift+z');await settled()
  await check('Keyboard redo reapplies parameter edit','stratum.store.document.nodes.find(n=>n.id==="copy").params.scale===1.2')
  await page.locator('#shelf-tools [data-type="sphere"]').click();await settled()
  sphere_id=await page.evaluate('stratum.selection[0]')
  await check('Shelf creates a real primitive node','stratum.store.document.nodes.at(-1).type==="sphere" && stratum.mesh.triangleCount>100')
  await page.locator('stratum-parameter-editor [data-keyframe="radius"]').click()
  await page.locator('stratum-timeline input.frame').fill('11');await page.locator('stratum-timeline input.frame').press('Tab')
  await page.locator('stratum-parameter-editor input[data-param="radius"][type="text"]').fill('3');await page.locator('stratum-parameter-editor input[data-param="radius"][type="text"]').press('Tab')
  await page.locator('stratum-timeline input.frame').fill('6');await page.locator('stratum-timeline input.frame').press('Tab');await settled()
  await check('Keyframed inspector edits auto-key and interpolate geometry','Math.abs(stratum.mesh.bounds().max[1]-2)<0.0001 && stratum.store.document.nodes.at(-1).keyframes.radius.length===2')
  await check('Inspector displays the evaluated animation value', '''document.getElementById("parameters").shadowRoot.querySelector('input[data-param="radius"][type="text"]').value==="2"''')
  await page.locator('stratum-parameter-editor [data-keyframe="radius"]').click();await page.locator('stratum-parameter-editor [data-keyframe="radius"]').click(modifiers=['Shift']);await settled()
  await check('Shift-click removes the current keyframe','stratum.store.document.nodes.at(-1).keyframes.radius.length===2')
  await page.locator('[data-bottomtab="animation"]').click()
  await check('Animation editor lists actual keyed channels','document.querySelectorAll("#animation tbody tr").length===2')
  await page.locator('[data-bottomtab="network"]').click()
  await page.locator('#command-btn').click();await page.locator('#operator-search').fill('transform');await page.locator('#operator-search').press('Enter');await settled()
  transform_id=await page.evaluate('stratum.selection[0]')
  await check('Command palette adds and wires a transform','stratum.store.document.nodes.at(-1).type==="transform" && !!stratum.store.document.nodes.at(-1).inputs[0]')
  await page.locator('stratum-parameter-editor input[data-param="translate"][data-axis="0"]').fill('=sin(t)*2')
  await page.locator('stratum-parameter-editor input[data-param="translate"][data-axis="0"]').press('Tab')
  await page.evaluate('stratum.setFrame(25)');await settled()
  await check('Frame-dependent transform expression changes actual bounds','Math.abs(stratum.mesh.bounds().center[0]-Math.sin(1)*2)<0.0001')
  await page.locator('#frame-nodes').click()
  node=page.locator(f'stratum-node-editor g[data-node="{transform_id}"] rect.body')
  old=await page.evaluate('(id)=>{const n=stratum.store.document.nodes.find(n=>n.id===id);return [n.x,n.y]}',transform_id)
  r=await node.bounding_box();await page.mouse.move(r['x']+r['width']*.5,r['y']+r['height']*.5);await page.mouse.down();await page.mouse.move(r['x']+r['width']*.5+45,r['y']+r['height']*.5+15,steps=6);await page.mouse.up();await settled()
  current=await page.evaluate('(id)=>{const n=stratum.store.document.nodes.find(n=>n.id===id);return [n.x,n.y]}',transform_id)
  assert current!=old;results.append({'test':'Pointer drag moves graph nodes and commits coordinates','pass':True})
  # Drag actual output/input ports to replace an existing graph connection.
  a=await page.locator(f'stratum-node-editor [data-output="{sphere_id}"]').bounding_box();b=await page.locator(f'stratum-node-editor [data-input="{transform_id}"]').bounding_box()
  await page.mouse.move(a['x']+a['width']/2,a['y']+a['height']/2);await page.mouse.down();await page.mouse.move(b['x']+b['width']/2,b['y']+b['height']/2,steps=10);await page.mouse.up();await settled()
  assert await page.evaluate('([a,b])=>stratum.store.document.nodes.find(n=>n.id===b).inputs[0]===a',[sphere_id,transform_id]);results.append({'test':'Pointer port wiring connects operators','pass':True})
  await page.locator('[data-bottomtab="spreadsheet"]').click()
  await check('Geometry spreadsheet shows cooked point data','document.querySelectorAll("#spreadsheet tbody tr").length>10')
  await page.locator('[data-bottomtab="performance"]').click()
  await check('Performance pane exposes genuine cook statistics','document.getElementById("performance").textContent.includes("ms")')
  await page.locator('[data-bottomtab="network"]').click()
  await page.locator('#camera-view').select_option('top')
  await check('Orthographic camera view changes projection','stratum.viewport.camera.orthographic === true')
  await page.locator('#shading-mode').select_option('normals')
  await check('Shading selector changes active renderer mode','stratum.viewport.options.mode==="normals"')
  await page.locator('#shading-mode').select_option('shaded');await page.locator('#camera-view').select_option('perspective')
  await page.locator('#toggle-grid').click()
  await check('Viewport grid toggle updates render state','stratum.viewport.options.grid===false')
  await page.locator('#toggle-grid').click()
  await page.locator('#theme-btn').click()
  await check('Light theme switches the application theme','document.body.classList.contains("theme-light")')
  await page.locator('#theme-btn').click()
  await page.locator('[data-tool="translate"]').click();await page.locator('#frame-scene').click();await page.wait_for_timeout(100)
  handle=page.locator('#gizmo line[data-axis="0"]');r=await handle.bounding_box()
  old=await page.evaluate('(id)=>stratum.store.document.nodes.find(n=>n.id===id).params.translate[0]',transform_id)
  await page.mouse.move(r['x']+r['width']*.75,r['y']+r['height']*.75);await page.mouse.down();await page.mouse.move(r['x']+r['width']*.75+40,r['y']+r['height']*.75,steps=8);await page.mouse.up();await settled()
  current=await page.evaluate('(id)=>stratum.store.document.nodes.find(n=>n.id===id).params.translate[0]',transform_id)
  assert current!=old and isinstance(current,(int,float));results.append({'test':'Viewport transform gizmo commits a geometry transform','pass':True})
  await page.locator('[data-tool="orbit"]').click()
  before=await page.evaluate('stratum.viewport.camera.yaw');r=await page.locator('#canvas').bounding_box()
  await page.mouse.move(r['x']+r['width']*.7,r['y']+r['height']*.6);await page.mouse.down();await page.mouse.move(r['x']+r['width']*.7+45,r['y']+r['height']*.6+15,steps=6);await page.mouse.up()
  assert await page.evaluate('stratum.viewport.camera.yaw')!=before;results.append({'test':'Pointer orbit updates camera orientation','pass':True})
  await page.locator('#import-file').set_input_files({'name':'triangle.obj','mimeType':'text/plain','buffer':b'v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3'})
  await settled()
  await check('OBJ file input imports editable geometry','stratum.store.document.nodes.at(-1).type==="obj" && stratum.mesh.triangleCount===1')
  await page.locator('#projects-btn').click();await page.locator('[data-preset="cloth"]').click();await settled()
  await check('Project example opens a simulated cloth scene','stratum.store.document.title.includes("Cloth") && stratum.mesh.triangleCount>0')
  await page.evaluate('stratum.setFrame(42)');await settled()
  await check('Timeline seeks and cooks simulated geometry','stratum.frame===42 && stratum.mesh.positions.every(Number.isFinite)')
  await page.locator('#projects-btn').click();await page.locator('[data-preset="basalt"]').click();await settled()
  await page.locator('#scene-tree [data-node="copy"]').click();await page.locator('#frame-nodes').click();await page.locator('#frame-scene').click();await page.wait_for_timeout(200)
  await check('Snapshot produces a valid PNG blob','async()=>{const blob=await stratum.viewport.snapshot(),b=new Uint8Array(await blob.arrayBuffer());return blob.type==="image/png"&&b[0]===137&&b[1]===80&&b.byteLength>10000;}')
  report={'checks':results,'passed':len(results),'pageErrors':errors,'backend':await page.evaluate('stratum.viewport.renderer.kind'),'secureContext':await page.evaluate('isSecureContext'),'inline':os.environ.get('STRATUM_INLINE_TEST')=='1','viewport':{'width':1600,'height':1000}}
  assert not errors,errors
  output=ROOT/'artifacts';output.mkdir(exist_ok=True)
  preview=await browser.new_page(viewport={'width':1600,'height':1000},device_scale_factor=1)
  await preview.set_content((ROOT/'dist/StratumFX.html').read_text(),wait_until='load')
  await preview.wait_for_function('window.stratum?.mesh?.instanceCount===1000 && !stratum.cooking')
  await preview.wait_for_timeout(300)
  await preview.screenshot(path=str(output/'studio-preview.png'))
  (output/'browser-report.json').write_text(json.dumps(report,indent=2))
  print(json.dumps(report,indent=2))
  await browser.close()
asyncio.run(main())
