import test from 'node:test';
import assert from 'node:assert/strict';
import { compileExpression, evaluateExpression, sampleKeys } from '../packages/core/src/expression.js';
import { createDocument, createNode, validateDocument, Engine, GraphStore, applyOperations, diffDocuments } from '../packages/core/src/graph.js';
import { defaultRegistry, createRegistry } from '../packages/core/src/nodes.js';
import { Mesh } from '../packages/geometry/src/mesh.js';
import { box } from '../packages/geometry/src/primitives.js';
import { preset, presetList } from '../app/presets.js';
function sample() { const d = createDocument(), a = createNode('box', { id: 'a' }), b = createNode('transform', { id: 'b', inputs: ['a'] }); d.nodes.push(a, b); d.outputId = 'b'; return d; }
test('expression precedence, parentheses, variables and functions', () => { assert.equal(evaluateExpression('2 + 3 * 4'), 14); assert.equal(evaluateExpression('2^3^2'), 512); assert.equal(evaluateExpression('(2+3)*4'), 20); assert.equal(evaluateExpression('=sin(t)*2', { t: Math.PI / 2 }), 2); assert.equal(evaluateExpression('$F + $T', { f: 3, t: 2 }), 5); assert.equal(evaluateExpression('x > 2 ? 4 : 5', { x: 3 }), 4); });
test('expression interpreter rejects arbitrary JS and prototype access', () => { for (const source of ['globalThis', 'window.alert(1)', 'process.exit()', 'x.constructor', 'x[0]', '1;2', '(()=>4)()', 'constructor(1)', '__proto__', 'while(1){}'])
    assert.throws(() => evaluateExpression(source, { x: 2 }), source); });
test('expression bounds reject infinity, excessive size and nesting', () => { assert.throws(() => evaluateExpression('1/0')); assert.throws(() => compileExpression('1+'.repeat(600) + '1')); assert.throws(() => evaluateExpression('('.repeat(80) + '1' + ')'.repeat(80))); });
test('linear and step keyframes interpolate and clamp endpoints', () => { const keys = [{ frame: 1, value: 0 }, { frame: 11, value: 10 }]; assert.equal(sampleKeys(keys, 6, 1), 5); assert.equal(sampleKeys(keys, -10, 1), 0); assert.equal(sampleKeys(keys, 20, 1), 10); keys[0].interpolation = 'step'; assert.equal(sampleKeys(keys, 6, 1), 0); });
for (const def of defaultRegistry.list())
    test(`operator ${def.type} cooks through the graph engine`, () => { const d = createDocument(), base = createNode('sphere', { id: 'base' }); Object.assign(base.params, { segments: 8, rings: 6 }); const node = createNode(def.type, { id: 'operator', inputs: Array.from({ length: def.inputs }, () => base.id) }); d.nodes.push(base, node); d.outputId = node.id; const { mesh } = new Engine().cook(d, 7); assert.ok(mesh instanceof Mesh); assert.ok(mesh.positions.every(Number.isFinite)); });
for (const item of presetList)
    test(`editable example ${item.id} validates and cooks`, () => { const d = preset(item.id); validateDocument(d); const { mesh } = new Engine().cook(d, item.id === 'cloth' ? 30 : item.id === 'rigid' ? 24 : 1); assert.ok(mesh.vertexCount > 0); assert.ok(mesh.instanceCount > 0); });
test('cooking reuses unchanged subgraphs and invalidates downstream only', () => { let d = sample(); const e = new Engine(); assert.equal(e.cook(d).stats.cooked, 2); assert.equal(e.cook(d).stats.cooked, 0); d = applyOperations(d, [{ kind: 'param', nodeId: 'b', key: 'translate', value: [4, 0, 0] }]); const r = e.cook(d); assert.equal(r.stats.cooked, 1); assert.equal(r.stats.cached, 1); assert.equal(r.mesh.bounds().center[0], 4); });
test('cycle creation is rejected without mutating the input document', () => { const d = sample(), before = JSON.stringify(d); assert.throws(() => applyOperations(d, [{ kind: 'connect', nodeId: 'b', slot: 0, sourceId: 'b' }]), /cycle/); assert.equal(JSON.stringify(d), before); });
test('operations reject prototype keys, invalid fields and invalid bypass', () => { const d = sample(); for (const op of [{ kind: 'param', nodeId: 'a', key: '__proto__', value: {} }, { kind: 'field', nodeId: 'a', key: 'type', value: 'rigid' }, { kind: 'field', nodeId: 'a', key: 'bypass', value: 'true' }])
    assert.throws(() => applyOperations(d, [op])); const poisoned = structuredClone(d); poisoned.nodes[0].params = JSON.parse('{"constructor":{}}'); assert.throws(() => validateDocument(poisoned)); });
test('mixed invalid batch is atomic', () => { const d = sample(); assert.throws(() => applyOperations(d, [{ kind: 'title', value: 'Should not apply' }, { kind: 'param', nodeId: 'b', key: 'noSuchParameter', value: 4 }])); assert.notEqual(d.title, 'Should not apply'); });
test('undo and redo restore parameter values and maintain an operation history', () => { const s = new GraphStore(sample()); s.commit([{ kind: 'param', nodeId: 'a', key: 'size', value: [2, 3, 4] }], 'Size'); assert.deepEqual(s.document.nodes[0].params.size, [2, 3, 4]); s.undo(); assert.deepEqual(s.document.nodes[0].params.size, [1, 1, 1]); s.redo(); assert.deepEqual(s.document.nodes[0].params.size, [2, 3, 4]); });
test('compensating undo leaves unrelated remote edits intact', () => { const s = new GraphStore(sample()); s.commit([{ kind: 'param', nodeId: 'a', key: 'size', value: [2, 2, 2] }]); s.replace(applyOperations(s.document, [{ kind: 'title', value: 'Remote title' }]), true); s.undo(); assert.equal(s.document.title, 'Remote title'); assert.deepEqual(s.document.nodes[0].params.size, [1, 1, 1]); });
test('node deletion disconnects dependencies; undo restores them', () => { const s = new GraphStore(sample()); s.commit([{ kind: 'remove', nodeId: 'a' }]); assert.equal(s.document.nodes[0].inputs[0], null); s.undo(); assert.equal(s.document.nodes.find(n => n.id === 'b').inputs[0], 'a'); validateDocument(s.document); });
test('document diff roundtrip restores all edited fields', () => { const a = sample(), b = applyOperations(a, [{ kind: 'title', value: 'Renamed' }, { kind: 'field', nodeId: 'b', key: 'x', value: 40 }, { kind: 'param', nodeId: 'a', key: 'size', value: [2, 2, 2] }, { kind: 'timeline', key: 'fps', value: 60 }]); assert.deepEqual(applyOperations(a, diffDocuments(a, b)), b); });
test('expressions drive transform vector components per frame', () => { const d = sample(); d.nodes[1].params.translate = ['=t*2', 0, 0]; const e = new Engine(); assert.equal(e.cook(d, 25).mesh.bounds().center[0], 2); assert.equal(e.cook(d, 49).mesh.bounds().center[0], 4); });
test('keyframed numeric parameters cook interpolated geometry', () => { const d = createDocument(), n = createNode('sphere'); n.keyframes.radius = [{ frame: 1, value: 1 }, { frame: 11, value: 3 }]; d.nodes = [n]; d.outputId = n.id; const m = new Engine().cook(d, 6).mesh; assert.ok(Math.abs(m.bounds().max[1] - 2) < 1e-5); });
test('custom registry nodes accept structurally compatible external geometry', () => { const r = createRegistry(); r.register('custom', { label: 'Custom', inputs: 0, cook: () => { const m = box(); return { ...m, get vertexCount() { return m.vertexCount; }, get instanceCount() { return m.instanceCount; }, get triangleCount() { return m.triangleCount; }, clone: () => m.clone(), bounds: () => m.bounds() }; } }); const d = createDocument(); d.nodes = [{ id: 'custom', type: 'custom', name: 'Custom', x: 0, y: 0, inputs: [], params: {}, keyframes: {}, bypass: false }]; d.outputId = 'custom'; assert.equal(new Engine(r).cook(d).mesh.vertexCount, 24); });
test('frame validation rejects NaN and unbounded values', () => { const e = new Engine(); assert.throws(() => e.cook(sample(), NaN)); assert.throws(() => e.cook(sample(), 1e30)); });
test('FPS changes invalidate time-dependent nodes at the same frame', () => { const d = preset('lattice'), engine = new Engine(), a = engine.cook(d, 25).mesh.instances.slice(); d.fps = 60; const result = engine.cook(d, 25); assert.notDeepEqual(result.mesh.instances, a); assert.ok(result.stats.cooked > 0); });
test('static attribute noise does not recook on timeline-only changes', () => { const d = createDocument(), a = createNode('sphere', { id: 's' }), b = createNode('noise', { id: 'n', inputs: ['s'] }); d.nodes = [a, b]; d.outputId = 'n'; const e = new Engine(); e.cook(d, 1); assert.equal(e.cook(d, 2).stats.cooked, 0); });
