const STYLE = `:host{display:block;min-width:0;background:var(--panel,#272c33);font:10px system-ui;color:var(--text,#cbd2da);user-select:none}.track{display:flex;align-items:center;height:43px;border-top:1px solid var(--border,#424952);border-bottom:1px solid var(--border,#424952);gap:12px;padding:0 15px}.playback{display:flex;gap:3px;align-items:center}.playback button{border:0;background:none;color:var(--text,#ccd2db);height:27px;min-width:27px;cursor:pointer;font-size:14px;border-radius:3px}.playback button:hover{background:#424951}.playback .play{background:#bc9558;color:#13191f;width:29px}.frame{width:46px;height:23px;background:var(--input,#1e242b);border:1px solid var(--border,#4a525e);border-radius:3px;color:#e5bd7c;text-align:center;font:11px monospace}.ruler{position:relative;flex:1;height:35px;min-width:50px;cursor:ew-resize;overflow:hidden}.ticks{position:absolute;inset:1px 0 3px;display:flex;justify-content:space-between;align-items:flex-end;color:var(--muted,#8d96a2)}.ticks span{height:27px;border-left:1px solid #56606c66;padding-left:3px;font:9px monospace}.head{position:absolute;top:0;bottom:0;width:2px;background:#d8a24a;pointer-events:none}.head:before{content:'';position:absolute;left:-4px;top:2px;border-left:5px solid transparent;border-right:5px solid transparent;border-top:7px solid #d8a24a}.key{position:absolute;bottom:1px;width:5px;height:5px;background:#d1a44f;transform:rotate(45deg)}.meta{display:flex;align-items:center;gap:6px;color:var(--muted,#96a0ae)}.meta input{width:42px;background:var(--input,#1e242b);border:1px solid var(--border,#414951);color:var(--text,#cbd1da);height:21px;text-align:center;font:10px monospace;border-radius:2px}.loop{accent-color:#cba766}`;
export class Timeline extends HTMLElement {
    constructor() { super(); this.attachShadow({ mode: 'open' }); this.start = 1; this.end = 240; this.fps = 24; this.frame = 1; this.playing = false; this.loop = true; this.keys = []; this.draw(); }
    configure({ start, end, fps, frame, keys }) { Object.assign(this, { start, end, fps, frame, keys: keys || [] }); this.draw(); }
    emit(type, detail) { this.dispatchEvent(new CustomEvent(type, { detail, bubbles: true, composed: true })); }
    setFrame(frame, notify = false) { if (!Number.isFinite(frame))
        return; this.frame = Math.max(this.start, Math.min(this.end, Math.round(frame))); const f = this.shadowRoot.querySelector('.frame'); if (f && this.shadowRoot.activeElement !== f)
        f.value = this.frame; const head = this.shadowRoot.querySelector('.head'); if (head)
        head.style.left = `${(this.frame - this.start) / Math.max(1, this.end - this.start) * 100}%`; if (notify)
        this.emit('frame-change', { frame: this.frame }); }
    toggle() { this.playing = !this.playing; this.shadowRoot.querySelector('.play').textContent = this.playing ? 'Ⅱ' : '▶'; this.emit('play-change', { playing: this.playing }); }
    draw() { this.shadowRoot.innerHTML = `<style>${STYLE}</style><div class="track"><div class="playback"><button data-action="first" title="First frame">Ⅰ◀</button><button data-action="prev" title="Previous frame">‹</button><button class="play" data-action="play" title="Play / pause (Space)">${this.playing ? 'Ⅱ' : '▶'}</button><button data-action="next" title="Next frame">›</button><button data-action="last" title="Last frame">▶Ⅰ</button></div><input class="frame" aria-label="Current frame" type="number" value="${this.frame}" min="${this.start}" max="${this.end}"><div class="ruler"><div class="ticks">${Array.from({ length: 11 }, (_, i) => `<span>${Math.round(this.start + (this.end - this.start) * i / 10)}</span>`).join('')}</div>${this.keys.map(k => `<i class="key" style="left:${(k.frame - this.start) / Math.max(1, this.end - this.start) * 100}%"></i>`).join('')}<div class="head"></div></div><div class="meta"><input aria-label="Start frame" data-meta="start" value="${this.start}"><span>—</span><input aria-label="End frame" data-meta="end" value="${this.end}"><input aria-label="Frames per second" data-meta="fps" value="${this.fps}"><span>fps</span><label title="Loop"><input type="checkbox" class="loop" ${this.loop ? 'checked' : ''} style="width:auto">↻</label></div></div>`; this.setFrame(this.frame); this.shadowRoot.querySelectorAll('[data-action]').forEach(b => b.onclick = () => { const a = b.dataset.action; if (a === 'play')
        this.toggle();
    else
        this.setFrame(a === 'first' ? this.start : a === 'last' ? this.end : this.frame + (a === 'prev' ? -1 : 1), true); }); this.shadowRoot.querySelector('.frame').onchange = e => this.setFrame(+e.target.value, true); this.shadowRoot.querySelectorAll('[data-meta]').forEach(e => e.onchange = () => this.emit('timeline-change', { key: e.dataset.meta, value: +e.value })); this.shadowRoot.querySelector('.loop').onchange = e => this.loop = e.target.checked; const r = this.shadowRoot.querySelector('.ruler'); let down = false; const set = e => { const rect = r.getBoundingClientRect(); this.setFrame(this.start + (e.clientX - rect.left) / rect.width * (this.end - this.start), true); }; r.onpointerdown = e => { r.setPointerCapture(e.pointerId); down = true; set(e); }; r.onpointermove = e => { if (down)
        set(e); }; r.onpointerup = () => down = false; r.onpointercancel = () => down = false; }
}
if (!customElements.get('stratum-timeline'))
    customElements.define('stratum-timeline', Timeline);
